version: "3.3"
services:
  tank-trample-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    image: tank-trample-client:0.2.3
    ports:
      - "3000:3000"

    pull_policy: build
    restart: always

  tank-trample-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: tank-trample-server:0.2.3
    ports:
      - "3001:3001"

    pull_policy: build
    restart: always
