version: "3.4"
services:
  
  # Client Version: 0.0.3 
  tank-trample-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"

  # Server Version: 0.0.2
  tank-trample-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
